name: Hello World
on:
  push:
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      group: bitrise-ghu-runner-group

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Setup Signal iOS
        run: |
          git clone --depth=1 --recurse-submodules https://github.com/signalapp/Signal-iOS
          cd Signal-iOS
          make dependencies
      - name: Build app
        run: |
          cd Signal-iOS
          env NSUnbufferedIO=YES xcodebuild build -scheme Signal -workspace Signal.xcworkspace CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  test:
    # The type of runner that the job will run on
    runs-on:
      group: bitrise-ghu-runner-group

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: Setup Signal iOS
        run: |
          git clone --depth=1 --recurse-submodules https://github.com/signalapp/Signal-iOS
          cd Signal-iOS
          make dependencies
      - name: Test app
        run: |
          cd Signal-iOS
          env NSUnbufferedIO=YES xcodebuild test -scheme Signal -workspace Signal.xcworkspace CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.6'
